# Generated by Django 4.0.4 on 2022-11-18 12:37

import albumstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path=albumstore.models.albumpath, recursive=True, verbose_name='Папка')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='Информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Альбом изображений',
            },
        ),
    ]
