# Generated by Django 4.0.4 on 2023-05-25 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumstore', '0002_albumstore_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumstore',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 25), null=True, verbose_name='Дата'),
        ),
    ]
