# Generated by Django 4.0.4 on 2023-06-18 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albumstore', '0003_albumstore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumstore',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 18, 13, 14, 23, 925455, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
    ]
