# Generated by Django 4.0.4 on 2022-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(choices=[('', ''), ('договор', 'договор'), ('АРБП', 'АРБП'), ('АТП', 'АТП'), ('однолинейная схема', 'однолинейная схема'), ('акт приемки узлов учета', 'акт приемки узлов учета'), ('паспорт', 'паспорт'), ('св-во о поверке', 'св-во о поверке'), ('прочие', 'прочие')], max_length=64, verbose_name='Тип документа')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('docfile', models.FileField(upload_to='docstore', verbose_name='Файл')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Документ',
            },
        ),
    ]
