# Generated by Django 4.0.4 on 2023-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_alter_docstore_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstore',
            name='docfile',
            field=models.FileField(max_length=256, upload_to='docstore', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='docstore',
            name='doctype',
            field=models.CharField(choices=[('', ''), ('договор', 'договор'), ('АРБП', 'АРБП'), ('АТП', 'АТП'), ('однолинейная схема', 'однолинейная схема'), ('акт приемки узлов учета', 'акт приемки узлов учета'), ('паспорт', 'паспорт'), ('св-во о поверке', 'св-во о поверке'), ('фото без крышки', 'фото без крышки'), ('отчет', 'отчет'), ('прочие', 'прочие')], max_length=64, verbose_name='Тип документа'),
        ),
    ]
