# Generated by Django 4.0.4 on 2023-01-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docstore', '0002_alter_docstore_doctype'),
        ('esadbsrv', '0003_delete_ttnexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTNExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttntype', models.CharField(blank=True, choices=[('Трансформатор тока', 'Трансформатор тока'), ('Трансформатор напряжения', 'Трансформатор напряжения'), ('Трансформатор комбинированный', 'Трансформатор комбинированный'), ('ИП прочие', 'ИП прочие')], max_length=64, null=True, verbose_name='Тип устроства')),
                ('ph', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('A-B', 'A-B'), ('B-C', 'B-C'), ('A-C', 'A-C'), ('A-B-C', 'A-B-C')], max_length=64, null=True, verbose_name='Фаза')),
                ('bl', models.CharField(blank=True, choices=[('', ''), ('абонент', 'абонент'), ('сети', 'сети'), ('сбыт', 'сбыт')], max_length=64, null=True, verbose_name='Принадлежность')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('ttnmodel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель')),
                ('fbdate', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('cldate', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('primarycoil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Первичная обмотка')),
                ('secondarycoil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вторичная обмотка')),
                ('pclass', models.CharField(blank=True, max_length=256, null=True, verbose_name='Класс точности трансформатора')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('mic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.mic')),
                ('ttndir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.atcttndirectory')),
            ],
            options={
                'verbose_name': 'Измерительный трансформатор',
            },
        ),
    ]
