# Generated by Django 4.0.4 on 2022-11-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('einst', '0001_initial'),
        ('docstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCMeterDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256, verbose_name='Модель ИП')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Код АТС')),
                ('regnumber', models.CharField(max_length=256, verbose_name='Номер в Госреестре СИ')),
                ('calibrationint', models.CharField(blank=True, max_length=256, null=True, verbose_name='Межповерочный интервал')),
                ('modification', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модификация ИП')),
                ('classae', models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс точности активной энергии')),
                ('classre', models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс точности реактивной энергии')),
                ('channelae', models.CharField(blank=True, max_length=8, null=True, verbose_name='Измерительные каналы активной энергии')),
                ('channelre', models.CharField(blank=True, max_length=8, null=True, verbose_name='Измерительные каналы реактивной энергии')),
                ('fabricator', models.CharField(blank=True, max_length=256, null=True, verbose_name='Завод-изготовитель')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Справочник измерительных приборов АТС',
            },
        ),
        migrations.CreateModel(
            name='ATCTTNDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Синтетический код справочника АТС')),
                ('ttntype', models.CharField(max_length=256, verbose_name='Тип устройства')),
                ('model', models.CharField(max_length=256, verbose_name='Модель трансформатора')),
                ('regnumber', models.CharField(max_length=256, verbose_name='Номер в Госреестре СИ')),
                ('modification', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модификация трансформатора')),
                ('pclass', models.CharField(blank=True, max_length=256, null=True, verbose_name='Класс точности трансформатора')),
                ('primarycoil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Первичная обмотка')),
                ('secondarycoil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вторичная обмотка')),
                ('colibrationint', models.CharField(blank=True, max_length=256, null=True, verbose_name='Межповерочный интервал')),
                ('fabric', models.CharField(blank=True, max_length=256, null=True, verbose_name='Завод-изготовитель')),
                ('sn', models.CharField(blank=True, max_length=256, null=True, verbose_name='Серийный номер')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Справочник АТС измерительных трансформаторов',
            },
        ),
        migrations.CreateModel(
            name='CDDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtype', models.CharField(default='', max_length=256, verbose_name='Тип устройства')),
                ('model', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель устройства')),
                ('fabric', models.CharField(blank=True, max_length=256, null=True, verbose_name='Завод-изготовитель')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='Информация')),
                ('rnote', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Справочник: устройства связи, УСПД, контроллеры',
            },
        ),
        migrations.CreateModel(
            name='MIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=256, null=True, verbose_name='Код АТС')),
                ('schnum', models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер на схеме')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('einst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='einst.einst')),
            ],
            options={
                'verbose_name': 'ИИК',
            },
        ),
        migrations.CreateModel(
            name='TTNExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttntype', models.CharField(blank=True, choices=[('Трансформатор тока', 'Трансформатор тока'), ('Трансформатор напряжения', 'Трансформатор напряжения'), ('Трансформатор комбинированный', 'Трансформатор комбинированный'), ('ИП прочие', 'ИП прочие')], max_length=64, null=True, verbose_name='Тип устроства')),
                ('ph', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('A-B', 'A-B'), ('B-C', 'B-C'), ('A-C', 'A-C'), ('A-B-C', 'A-B-C')], max_length=64, null=True, verbose_name='Фаза')),
                ('bl', models.CharField(blank=True, choices=[('', ''), ('абонент', 'абонент'), ('сети', 'сети'), ('сбыт', 'сбыт')], max_length=64, null=True, verbose_name='Принадлежность')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('ttnmodel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель')),
                ('fbdate', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('cldate', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('primarycoil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Первичная обмотка')),
                ('secondarycoil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вторичная обмотка')),
                ('pclass', models.CharField(blank=True, max_length=256, null=True, verbose_name='Класс точности трансформатора')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('mic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.mic')),
                ('ttndir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.atcttndirectory')),
            ],
            options={
                'verbose_name': 'Измерительный трансформатор',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl', models.CharField(choices=[('', ''), ('абонент', 'абонент'), ('сети', 'сети'), ('сбыт', 'сбыт')], max_length=64, verbose_name='Принадлежность')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('mtrmodel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель')),
                ('fbdate', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('cldate', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('classae', models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс точности активной энергии')),
                ('classre', models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс точности реактивной энергии')),
                ('channelae', models.CharField(blank=True, max_length=8, null=True, verbose_name='Измерительные каналы активной энергии')),
                ('channelre', models.CharField(blank=True, max_length=8, null=True, verbose_name='Измерительные каналы реактивной энергии')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('mic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.mic')),
                ('mtrdir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.atcmeterdir')),
            ],
            options={
                'verbose_name': 'Счетчик, измерительный прибор',
            },
        ),
        migrations.CreateModel(
            name='CommDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('cdmodel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель')),
                ('fbdate', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('addr', models.CharField(blank=True, max_length=16, null=True, verbose_name='Сетевой адрес')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='Информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('cddir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.cddirectory')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('einst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='einst.einst')),
            ],
            options={
                'verbose_name': 'Устройства связи, УСПД, контроллеры',
            },
        ),
    ]
