# Generated by Django 4.0.4 on 2023-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_info'),
        ('esadbsrv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mic',
            name='channels',
            field=models.ManyToManyField(to='channel.channel'),
        ),
    ]
