# Generated by Django 4.0.4 on 2023-01-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esadbsrv', '0002_mic_channels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TTNExample',
        ),
    ]
