# Generated by Django 4.0.4 on 2023-01-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esadbsrv', '0003_delete_ttnexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meter',
        ),
    ]
