# Generated by Django 4.0.4 on 2023-01-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esadbsrv', '0004_delete_meter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommDevice',
        ),
    ]
