# Generated by Django 4.0.4 on 2023-01-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esadbsrv', '0005_delete_commdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mic',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='mic',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='mic',
            name='einst',
        ),
    ]
