# Generated by Django 4.0.4 on 2023-01-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_alter_meter_mic'),
        ('ttnexample', '0002_alter_ttnexample_mic'),
        ('esadbsrv', '0006_remove_mic_channels_remove_mic_docs_remove_mic_einst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MIC',
        ),
    ]
