# Generated by Django 4.0.4 on 2023-01-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esadbsrv', '0007_delete_mic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cddirectory',
            old_name='rnote',
            new_name='note',
        ),
    ]
