# Generated by Django 4.0.4 on 2023-06-18 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdiskstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdiskfolder',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 18, 13, 16, 21, 894677, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
    ]
