# Generated by Django 4.0.4 on 2023-08-13 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdiskstorage', '0002_alter_gdiskfolder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdiskfolder',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 13, 10, 13, 41, 112751, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
    ]
