# Generated by Django 4.0.4 on 2023-09-17 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdiskstorage', '0003_alter_gdiskfolder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdiskfolder',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
    ]
