# Generated by Django 4.0.4 on 2023-01-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0002_alter_channel_info'),
        ('einst', '0004_einst_project'),
        ('docstore', '0002_alter_docstore_doctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=256, null=True, verbose_name='Код АТС')),
                ('schnum', models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер на схеме')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('channels', models.ManyToManyField(to='channel.channel')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('einst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='einst.einst')),
            ],
            options={
                'verbose_name': 'ИИК',
            },
        ),
    ]
