# Generated by Django 4.0.4 on 2023-08-13 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NXCFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2023, 8, 13, 10, 13, 41, 114750, tzinfo=utc), null=True, verbose_name='Дата')),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, recursive=True, verbose_name='Папка')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='Информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Папка на NextCloud by ESA',
            },
        ),
    ]
