# Generated by Django 4.0.4 on 2023-09-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_iccid_channel_ip_channel_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='iccid',
            new_name='ccid',
        ),
    ]
