# Generated by Django 4.0.4 on 2023-01-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esadbsrv', '0005_delete_commdevice'),
        ('docstore', '0002_alter_docstore_doctype'),
        ('einst', '0004_einst_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl', models.CharField(choices=[('', ''), ('абонент', 'абонент'), ('сети', 'сети'), ('сбыт', 'сбыт')], max_length=64, verbose_name='Принадлежность')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('cdmodel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель')),
                ('fbdate', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('addr', models.CharField(blank=True, max_length=16, null=True, verbose_name='Сетевой адрес')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='Информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('cddir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.cddirectory')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('einst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='einst.einst')),
            ],
            options={
                'verbose_name': 'Устройства связи, УСПД, контроллеры',
            },
        ),
    ]
