# Generated by Django 4.0.4 on 2023-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commdevice', '0003_commdevice_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdevice',
            name='addr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Сетевой идентификатор'),
        ),
        migrations.AlterField(
            model_name='commdevice',
            name='addrtype',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Тип сетевого идентификатора'),
        ),
    ]
