# Generated by Django 4.0.4 on 2023-09-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commdevice', '0004_alter_commdevice_addr_alter_commdevice_addrtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdevice',
            name='bl',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Принадлежность'),
        ),
    ]
