# Generated by Django 4.0.4 on 2023-09-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commdevice', '0005_alter_commdevice_bl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commdevice',
            name='einst',
        ),
    ]
