# Generated by Django 4.0.4 on 2023-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commdevice', '0006_remove_commdevice_einst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdevice',
            name='bl',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Принадлежность'),
        ),
    ]
