# Generated by Django 4.0.4 on 2022-11-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albumstore', '0001_initial'),
        ('docstore', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('contactinfo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Контакты')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Примечание')),
                ('albums', models.ManyToManyField(to='albumstore.albumstore')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.organization')),
            ],
            options={
                'verbose_name': 'Объект, электроустановка, сооружение, подстанция',
            },
        ),
    ]
