# Generated by Django 4.0.4 on 2022-12-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_info'),
        ('einst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einst',
            name='channels',
            field=models.ManyToManyField(to='channel.channel'),
        ),
    ]
