# Generated by Django 4.0.4 on 2022-12-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('einst', '0003_einst_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='einst',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
