# Generated by Django 4.0.4 on 2023-01-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esadbsrv', '0004_delete_meter'),
        ('docstore', '0002_alter_docstore_doctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl', models.CharField(choices=[('', ''), ('абонент', 'абонент'), ('сети', 'сети'), ('сбыт', 'сбыт')], max_length=64, verbose_name='Принадлежность')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер')),
                ('mtrmodel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель')),
                ('fbdate', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('cldate', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('classae', models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс точности активной энергии')),
                ('classre', models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс точности реактивной энергии')),
                ('channelae', models.CharField(blank=True, max_length=8, null=True, verbose_name='Измерительные каналы активной энергии')),
                ('channelre', models.CharField(blank=True, max_length=8, null=True, verbose_name='Измерительные каналы реактивной энергии')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общая информация')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('docs', models.ManyToManyField(to='docstore.docstore')),
                ('mic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.mic')),
                ('mtrdir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esadbsrv.atcmeterdir')),
            ],
            options={
                'verbose_name': 'Счетчик, измерительный прибор',
            },
        ),
    ]
