# Generated by Django 4.0.4 on 2023-01-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mic', '0001_initial'),
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='mic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mic.mic'),
        ),
    ]
